#


## SyncTimeoutException
[source](https://github.com/estudio89/estudio89/maestro-python/blob/master/maestro/core/exceptions.py/#L1)
```python 
SyncTimeoutException(
   elapsed_time, max_duration_seconds: 'int'
)
```


---
Raised when the synchronization session exceeds its timeout.

----


## ItemNotFoundException
[source](https://github.com/estudio89/estudio89/maestro-python/blob/master/maestro/core/exceptions.py/#L9)
```python 
ItemNotFoundException(
   item_type: 'str', id: 'str'
)
```


